# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0007_auto_20160617_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='expected_result',
        ),
        migrations.AddField(
            model_name='bet',
            name='expected_away_goals',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='expected_home_goals',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
